# Generated by Django 2.1.2 on 2020-09-03 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.date(1900, 1, 1), null=True),
        ),
    ]
