# Generated by Django 2.1.2 on 2020-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200903_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='birthday',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
    ]
